# Generated by Django 4.2.11 on 2025-03-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
